use lottery;
drop table doubleball;
CREATE TABLE IF NOT EXISTS `doubleball` (
  `IDENTIFIER` BIGINT NOT NULL ,
  `GENERATE_TIME` VARCHAR(12)  NOT NULL ,
  `RED1` VARCHAR(2)  NOT NULL ,
  `RED2` VARCHAR(2)   NOT NULL ,
  `RED3` VARCHAR(2)   NOT NULL ,
  `RED4` VARCHAR(2)   NOT NULL ,
  `RED5` VARCHAR(2)  NOT NULL ,
  `RED6` VARCHAR(2)  NOT NULL ,
  `BLUE` VARCHAR(2)  NOT NULL ,
  PRIMARY KEY (`IDENTIFIER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

delete  from doubleball where 1=1;